# Generated by Django 3.1.5 on 2021-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0004_db_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_apis',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='接口名'),
        ),
    ]
