# Generated by Django 3.1.5 on 2021-01-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0005_auto_20210127_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_apis',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
