# Generated by Django 3.0.6 on 2021-01-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0006_auto_20210127_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_apis',
            name='last_api_body',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='last_body_method',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
