# Generated by Django 3.1.5 on 2021-01-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0009_db_apis_log_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
