# Generated by Django 3.1.5 on 2021-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0011_db_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_step',
            name='Case_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_step',
            name='api_body',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='db_step',
            name='api_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
