# Generated by Django 3.1.5 on 2021-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0012_auto_20210201_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_step',
            name='api_body_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
