# Generated by Django 3.1 on 2021-02-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0013_auto_20210201_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_step',
            name='mock_res',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
