# Generated by Django 3.1 on 2021-02-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0017_db_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('host', models.TextField(null=True)),
            ],
        ),
    ]
